# Generated by Django 5.2.8 on 2025-11-17 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("location", models.CharField(max_length=255)),
                ("photo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "events",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_certified", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eventapp_user_set",
                        related_query_name="eventapp_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eventapp_user_set",
                        related_query_name="eventapp_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("num_likes", models.IntegerField(default=0)),
                ("num_saves", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="EventApp.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="EventApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="EventApp.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_events",
                        to="EventApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "event_favorites",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                db_column="creator_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to="EventApp.user",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="EventApp.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="EventApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("event", "Event"), ("post", "Post")], max_length=10
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_column="event_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="EventApp.event",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        db_column="post_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="EventApp.post",
                    ),
                ),
            ],
            options={
                "db_table": "photos",
                "ordering": ["uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "event"],
                        name="photos_content_1dd6f1_idx",
                    ),
                    models.Index(
                        fields=["content_type", "post"],
                        name="photos_content_04b72c_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("event__isnull", False), ("post__isnull", True)),
                            models.Q(("event__isnull", True), ("post__isnull", False)),
                            _connector="OR",
                        ),
                        name="photo_either_event_or_post",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-created_at"], name="posts_created_2e2442_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["user"], name="posts_user_id_05c508_idx"),
        ),
        migrations.AddIndex(
            model_name="eventfavorite",
            index=models.Index(
                fields=["user", "event"], name="event_favor_user_id_58fcff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventfavorite",
            unique_together={("user", "event")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="events_date_e70fc0_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["creator"], name="events_creator_a4cbbe_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post"], name="comments_post_id_7ee550_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="comments_created_d5740c_idx"
            ),
        ),
    ]
