# Generated by Django 5.2.8 on 2025-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0003_alter_photo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo_url",
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(blank=True, default="dall.png", upload_to=""),
        ),
    ]
