# Generated by Django 6.0 on 2026-01-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_remove_event_photo_url_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='dall.png', upload_to='photos/'),
        ),
    ]
